[package]
name = "zktls-prover"
version = "0.1.0"
edition = "2024"

[dependencies]
pico-sdk = { workspace = true }
bincode = "1.3.3"
serde = { version = "1.0", features = ["derive"] }
alloy-sol-types = "0.8.0"
hex = "0.4"
structopt = "0.3"
